let MCQS = [{
    question: "Inside which HTML element do we put the JavaScript?",
    choice1: "<js>",
    choice2: "<script>",
    choice3: "<scripting>",
    choice4: "<javascript>",
    answer: "2. <script>",
},
    {
        question: "How do you create a function in JavaScript?",
    choice1: "function myFunction()",
    choice2: "function:myFunction()",
    choice3: "function = myFunction()",
    choice4: "myFunction=",
    answer: "1. function myFunction()",
},
    {
        question: "How do you write an IF statement in JavaScript?",
    choice1: "if i = 5",
    choice2: "if i == 5 then",
    choice3: "if i = 5 then",
    choice4: " if (i == 5)",
    answer: "4. if (i == 5)",
},
    {
        question: "How does a FOR loop start?",
    choice1: "for (i <= 5; i++)",
    choice2: "for i = 1 to 5",
    choice3: "for (i=0; i <= 5; i++)",
    choice4: "for (i = 0; i <= 5)",
    answer: "3. for (i=0; i <= 5; i++)",
},
    {
        question: "How can you add a comment in a JavaScrpit?",
    choice1: "//This is a comment",
    choice2: "<!-- This is a comment -->",
    choice3: "-This is a comment-",
    choice4: "'This is a comment'",
    answer: "1. //This is a comment",
},
    {
        question: "What is the correct way to write a JavaScript array?",
    choice1: "var colors = (1:"red", 2:"green", 3:"blue")",
    choice2: "var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")",
    choice3: "var colors = ["red", "green", "blue"]",
    choice4: "var colors = "red", "green", "blue"",
    answer: "3. var colors = ["red", "green", "blue"]",
},
    {
        question: "How do you find the number with the highest value of x and y?",
    choice1: "Math.ceil(x, y)",
    choice2: "ceil(x, y)",
    choice3: "top(x, y)",
    choice4: "Math.max(x, y)",
    answer: "4. Math.max(x, y)",
},
    {
        question: "Which event occurs when the user clicks on an HTML element?",
    choice1: "onmouseclick",
    choice2: "onclick",
    choice3: "onmouseover",
    choice4: "clickedon",
    answer: "2. onclick",
},
    {
        question: "How do you declare a JavaScript variable?",
    choice1: "var-thisName",
    choice2: "var thisName",
    choice3: "variable thisName",
    choice4: "v thisName",
    answer: "2. var thisName",
},
    {
        question: "Which operator is used to assign a value to a variable?",
    choice1: "-",
    choice2: "*",
    choice3: "~",
    choice4: "=",
    answer: "4. =",
},
]
